### ISSUE TITLE
Using jq-likes takes a long time on the universal image, but not on node

### ISSUE THREAD

**Issue by craiglpeters** [eitsupi/devcontainer-features#61] opened 2023-03-03 23:46 UTC
Hey there - hanks for contributing the `jq-likes` feature!

I am trying to figure out why the `setup_yq_completions()` step of https://github.com/eitsupi/devcontainer-features/blob/main/src/jq-likes/install.sh#L99 takes 10 minutes when using the [`universal`](https://github.com/devcontainers/images/tree/main/src/universal) dev container image on Codespaces, but goes fast on the [`javascript-node`](https://github.com/devcontainers/images/tree/main/src/javascript-node) image. Any thoughts?

**Comment by eitsupi** [comment] 2023-03-04 11:56
Thank you for letting me know about that.

Is it likely that you have a large number of files in your home directory on the universal image?
If so, the following lines will take a long time to execute.
https://github.com/eitsupi/devcontainer-features/blob/af60bc8a47c03d97971a1effd9631ef7f1f3bd97/src/jq-likes/install.sh#L152-L155

**Comment by eitsupi** [comment] 2023-03-04 13:28
I added a universe image to the test but could not reproduce it.
https://github.com/eitsupi/devcontainer-features/actions/runs/4331155877/jobs/7562821504#step:4:4229

```log
===========================================================================
[2023-03-04T13:17:01.755Z] 

[2023-03-04T13:17:01.755Z] #16 0.407 Feature       : ./jq-likes
[2023-03-04T13:17:01.755Z] 

[2023-03-04T13:17:01.755Z] #16 0.407 Description   : Installs jq and jq like command line tools (yq, gojq).
[2023-03-04T13:17:01.755Z] 

[2023-03-04T13:17:01.755Z] #16 0.407 Id            : Unknown
[2023-03-04T13:17:01.756Z] 

[2023-03-04T13:17:01.756Z] #16 0.407 Version       : 1.0.0
[2023-03-04T13:17:01.756Z] 

[2023-03-04T13:17:01.756Z] #16 0.407 Documentation : https://github.com/eitsupi/devcontainer-features/tree/main/src/jq-likes
[2023-03-04T13:17:01.756Z] 

[2023-03-04T13:17:01.756Z] #16 0.407 Options       :
[2023-03-04T13:17:01.757Z] 

[2023-03-04T13:17:01.757Z] #16 0.407     JQVERSION="none"
[2023-03-04T13:17:01.757Z] 

[2023-03-04T13:17:01.757Z] #16 0.407     YQVERSION="latest"
[2023-03-04T13:17:01.757Z] 

[2023-03-04T13:17:01.757Z] #16 0.407     GOJQVERSION="latest"
[2023-03-04T13:17:01.758Z] 

[2023-03-04T13:17:01.758Z] #16 0.407 ===========================================================================
[2023-03-04T13:17:01.758Z] 

[2023-03-04T13:17:02.200Z] #16 0.714 YQ_VERSION=4.31.2
#16 0.852 GOJQ_VERSION=0.12.12

[2023-03-04T13:17:02.350Z] #16 0.866 Downloading yq...

[2023-03-04T13:17:02.623Z] #16 1.275 /tmp/yq /tmp/dev-container-features/jq-likes_10

[2023-03-04T13:17:02.773Z] #16 1.284 /tmp/dev-container-features/jq-likes_10
#16 1.293 Installing bash completion...
#16 1.304 Installing zsh completion...

[2023-03-04T13:19:02.184Z] #16 120.7 Downloading gojq...

[2023-03-04T13:19:02.485Z] #16 121.0 Installing zsh completion...
#16 121.0 Done!

[2023-03-04T13:19:02.597Z] #16 DONE 121.2s
```

I think we need the devcontainer.json that reproduces the problem.

**Comment by craiglpeters** [comment] 2023-03-04 15:58
Thank you for looking into this. This is the dev containter where you can reproduce the problem https://github.com/Security-Knowledge-Framework/skf-examination-platform/tree/okikiojo/devcontainer-optimize/.devcontainer

**Comment by eitsupi** [comment] 2023-03-04 21:27
Thanks, but it does not seem based on the universe image...

**Comment by eitsupi** [comment] 2023-03-04 21:59
Are there possible interactions between Features?
Does the same issue occur if you change the installation order?
https://containers.dev/implementors/features/#installation-order

**Comment by eitsupi** [comment] 2023-03-05 09:43
@craiglpeters I tried to build on Codespaces, but the logs were instantaneous and I couldn't even copy them (In other words, the problem did not occur.).
Can you please confirm if the problem still occurs on your end?

**Comment by eitsupi** [comment] 2023-04-01 10:35
I am closing this for now due to lack of information.
If the problem still occurs please feel free to let me know and reopen it.

**Closed by eitsupi** 2023-04-01 10:35 UTC
Labels: bug, needs more info
